export interface DomainConfig {
  key: string;
  name: string;
  projectName: string;
  description: string;
  summary: string;
  startOffsetDays: number;
  durationDays: number;
  epics: string[];
  components: string[];
  integrations: string[];
  personas: string[];
  workflows: string[];
  qaFocus: string[];
  incidentThemes: string[];
}

export const domainConfigs: DomainConfig[] = [
  {
    key: 'fintech',
    name: 'Fintech',
    projectName: 'LedgerPay Core Banking Modernization',
    description: 'Modernize payments, ledger posting, risk controls, and reconciliation for a regulated digital wallet.',
    summary: 'Enterprise backlog covering payment orchestration, KYC, ledger integrity, reconciliation, observability, and compliance releases.',
    startOffsetDays: 300,
    durationDays: 260,
    epics: ['KYC onboarding', 'ACH settlement', 'Card authorization', 'Ledger reconciliation', 'Fraud rules engine', 'Dispute operations', 'PCI evidence automation', 'Treasury reporting'],
    components: ['wallet-api', 'ledger-service', 'risk-service', 'reconciliation-worker', 'admin-portal', 'mobile-wallet', 'card-gateway', 'audit-exporter'],
    integrations: ['Stripe Issuing', 'Plaid', 'Dwolla ACH', 'Socure KYC', 'Snowflake finance mart', 'PagerDuty'],
    personas: ['payment operations analyst', 'fraud reviewer', 'treasury manager', 'compliance officer', 'mobile wallet customer'],
    workflows: ['manual review queue', 'same-day ACH cutoff', 'ledger replay', 'chargeback intake', 'risk hold release'],
    qaFocus: ['negative balance prevention', 'duplicate webhook delivery', 'idempotency replay', 'PCI redaction', 'settlement day rollover'],
    incidentThemes: ['ACH file rejected by bank partner', 'ledger drift after retry storm', 'card auth latency spike', 'KYC provider timeout'],
  },
  {
    key: 'ecommerce',
    name: 'Ecommerce',
    projectName: 'Mercato Omnichannel Commerce Platform',
    description: 'Scale storefront, checkout, promotions, inventory, and fulfillment across web, mobile, and marketplace channels.',
    summary: 'Backlog for checkout reliability, catalog scale, seller operations, promotions, order management, and peak-season readiness.',
    startOffsetDays: 250,
    durationDays: 220,
    epics: ['Checkout conversion', 'Promotion engine', 'Inventory allocation', 'Seller onboarding', 'Returns workflow', 'Marketplace search', 'Loyalty program', 'Peak sale readiness'],
    components: ['storefront-web', 'checkout-api', 'catalog-service', 'inventory-service', 'seller-console', 'order-worker', 'mobile-shop', 'recommendation-api'],
    integrations: ['Adyen', 'Algolia', 'Shopify Plus', 'Braze', 'SAP inventory feed', 'Segment'],
    personas: ['shopper', 'seller success manager', 'warehouse picker', 'category manager', 'customer support agent'],
    workflows: ['cart recovery', 'split shipment', 'return authorization', 'coupon stacking', 'flash sale throttle'],
    qaFocus: ['cart merge edge cases', 'tax recalculation', 'promotion conflicts', 'inventory oversell', 'guest checkout'],
    incidentThemes: ['payment capture failures', 'catalog index lag', 'coupon abuse spike', 'warehouse feed delay'],
  },
  {
    key: 'healthcare',
    name: 'Healthcare',
    projectName: 'CareBridge Patient Coordination Suite',
    description: 'Build HIPAA-conscious care coordination, scheduling, referrals, and patient communications for regional clinics.',
    summary: 'Clinical operations backlog spanning appointment scheduling, patient messaging, referrals, EHR sync, and audit trails.',
    startOffsetDays: 210,
    durationDays: 210,
    epics: ['Patient intake', 'Referral routing', 'Appointment scheduling', 'EHR synchronization', 'Care plan tasks', 'Secure messaging', 'Claims attachment', 'HIPAA audit reporting'],
    components: ['patient-portal', 'scheduler-api', 'ehr-sync-worker', 'provider-console', 'notification-service', 'claims-export', 'mobile-care', 'audit-log-service'],
    integrations: ['Epic FHIR', 'Twilio Verify', 'Availity', 'Surescripts', 'Datadog RUM', 'Okta'],
    personas: ['care coordinator', 'primary care physician', 'patient', 'billing specialist', 'clinic administrator'],
    workflows: ['referral triage', 'appointment reschedule', 'lab result follow-up', 'care gap outreach', 'prior authorization'],
    qaFocus: ['PHI masking', 'timezone scheduling', 'FHIR retry behavior', 'consent checks', 'message delivery audit'],
    incidentThemes: ['EHR sync backlog', 'SMS delivery degradation', 'appointment double-booking', 'claim attachment rejection'],
  },
  {
    key: 'logistics',
    name: 'Logistics',
    projectName: 'RouteOps Fleet Visibility Platform',
    description: 'Improve shipment tracking, dispatch planning, driver mobile workflows, and carrier integrations.',
    summary: 'Backlog for route optimization, live tracking, exception handling, EDI integrations, and dispatch operations.',
    startOffsetDays: 180,
    durationDays: 200,
    epics: ['Dispatch board', 'Route optimization', 'Shipment tracking', 'Driver mobile app', 'Carrier EDI', 'Exception management', 'Proof of delivery', 'Fleet maintenance'],
    components: ['dispatch-web', 'routing-engine', 'tracking-api', 'driver-mobile', 'edi-gateway', 'notification-worker', 'telematics-ingest', 'pod-service'],
    integrations: ['Samsara', 'Project44', 'FourKites', 'Twilio', 'NetSuite', 'SFTP EDI partner'],
    personas: ['dispatcher', 'driver', 'warehouse supervisor', 'carrier manager', 'shipper support agent'],
    workflows: ['late shipment escalation', 'route resequencing', 'driver check-in', 'dock appointment', 'POD upload'],
    qaFocus: ['GPS gap handling', 'offline mobile sync', 'EDI duplicate files', 'route constraint validation', 'photo upload retry'],
    incidentThemes: ['tracking ingest lag', 'route optimizer timeout', 'EDI 214 mapping error', 'driver app crash on upload'],
  },
  {
    key: 'ai-saas',
    name: 'AI SaaS',
    projectName: 'PromptOps Enterprise AI Workspace',
    description: 'Deliver multi-tenant AI workspace features for prompt management, evaluations, governance, and billing.',
    summary: 'AI SaaS backlog covering model gateway reliability, prompt registry, eval pipelines, tenant controls, and usage analytics.',
    startOffsetDays: 140,
    durationDays: 180,
    epics: ['Prompt registry', 'Evaluation pipelines', 'Model gateway', 'Tenant governance', 'Usage metering', 'Knowledge ingestion', 'Admin analytics', 'Safety policy enforcement'],
    components: ['model-gateway', 'prompt-studio', 'eval-runner', 'tenant-api', 'billing-meter', 'vector-ingest', 'admin-dashboard', 'policy-engine'],
    integrations: ['OpenAI API', 'Azure OpenAI', 'Pinecone', 'Stripe Billing', 'Slack', 'Datadog'],
    personas: ['AI platform admin', 'prompt engineer', 'security reviewer', 'finance owner', 'application developer'],
    workflows: ['prompt approval', 'offline evaluation', 'tenant quota increase', 'knowledge sync', 'model fallback'],
    qaFocus: ['token accounting', 'tenant data isolation', 'streaming cancellation', 'eval reproducibility', 'rate-limit backoff'],
    incidentThemes: ['model provider outage', 'metering undercount', 'vector ingest queue growth', 'prompt deployment rollback'],
  },
  {
    key: 'hrm',
    name: 'HRM',
    projectName: 'PeopleFlow Workforce Management',
    description: 'Build HR lifecycle, time off, performance reviews, payroll exports, and employee self-service workflows.',
    summary: 'HRM backlog for onboarding, leave policies, org charts, performance cycles, payroll handoff, and employee records.',
    startOffsetDays: 120,
    durationDays: 170,
    epics: ['Employee onboarding', 'Time-off policies', 'Performance reviews', 'Org chart', 'Payroll exports', 'Document management', 'Benefits enrollment', 'Manager self-service'],
    components: ['employee-portal', 'hr-admin', 'leave-service', 'review-workflow', 'payroll-exporter', 'document-vault', 'org-service', 'mobile-employee'],
    integrations: ['Workday', 'ADP', 'DocuSign', 'Okta', 'Google Workspace', 'Slack'],
    personas: ['HR business partner', 'employee', 'line manager', 'payroll specialist', 'benefits administrator'],
    workflows: ['new hire checklist', 'leave approval', 'review calibration', 'payroll cutoff', 'document acknowledgement'],
    qaFocus: ['manager hierarchy changes', 'holiday calendar overlap', 'payroll file validation', 'document permissions', 'review anonymity'],
    incidentThemes: ['payroll export mismatch', 'leave balance drift', 'SSO group sync delay', 'document preview outage'],
  },
  {
    key: 'crm',
    name: 'CRM',
    projectName: 'RevenueDesk CRM RevOps Platform',
    description: 'Unify account management, pipeline automation, campaign attribution, and customer success workflows.',
    summary: 'CRM backlog for opportunity management, activity capture, lead routing, forecasting, account health, and integrations.',
    startOffsetDays: 100,
    durationDays: 160,
    epics: ['Lead routing', 'Opportunity pipeline', 'Account health', 'Activity capture', 'Forecasting', 'Campaign attribution', 'Customer success playbooks', 'Contract renewal'],
    components: ['crm-web', 'accounts-api', 'pipeline-service', 'activity-ingest', 'forecast-worker', 'marketing-sync', 'cs-dashboard', 'renewals-service'],
    integrations: ['Salesforce', 'HubSpot', 'Marketo', 'Gong', 'DocuSign', 'Snowflake'],
    personas: ['sales rep', 'account executive', 'sales manager', 'customer success manager', 'RevOps analyst'],
    workflows: ['lead assignment', 'stage progression', 'forecast rollup', 'QBR preparation', 'renewal risk review'],
    qaFocus: ['duplicate account merge', 'stage validation', 'timezone activity capture', 'forecast permissions', 'campaign attribution windows'],
    incidentThemes: ['Salesforce sync failure', 'forecast rollup regression', 'duplicate lead import', 'webhook backlog'],
  },
  {
    key: 'erp',
    name: 'ERP',
    projectName: 'AtlasERP Finance and Procurement',
    description: 'Modernize procurement, AP approvals, budget controls, supplier management, and financial close.',
    summary: 'ERP backlog covering purchase requests, approval routing, vendor master data, AP automation, budgets, and close controls.',
    startOffsetDays: 80,
    durationDays: 150,
    epics: ['Purchase requisition', 'Approval routing', 'Vendor master data', 'Accounts payable', 'Budget controls', 'Financial close', 'Inventory valuation', 'Audit evidence'],
    components: ['procurement-web', 'approval-engine', 'vendor-service', 'ap-worker', 'budget-api', 'close-dashboard', 'inventory-costing', 'audit-exporter'],
    integrations: ['SAP S/4HANA', 'Coupa', 'NetSuite', 'DocuSign', 'Workday cost centers', 'Power BI'],
    personas: ['procurement analyst', 'finance controller', 'AP specialist', 'department approver', 'internal auditor'],
    workflows: ['purchase request approval', 'three-way match', 'vendor onboarding', 'month-end close', 'budget exception'],
    qaFocus: ['approval delegation', 'currency rounding', 'invoice matching', 'cost center sync', 'audit trail completeness'],
    incidentThemes: ['AP batch rejected', 'budget rule misfire', 'vendor sync duplicate', 'close dashboard stale data'],
  },
  {
    key: 'education',
    name: 'Education',
    projectName: 'LearnSphere Digital Campus',
    description: 'Develop learning management, assessments, cohort analytics, content authoring, and student support flows.',
    summary: 'Education backlog for course delivery, grading, proctoring integrations, learner analytics, content operations, and accessibility.',
    startOffsetDays: 55,
    durationDays: 130,
    epics: ['Course authoring', 'Assessment delivery', 'Gradebook', 'Cohort analytics', 'Student support', 'Live classroom', 'Content library', 'Accessibility compliance'],
    components: ['learner-web', 'instructor-console', 'assessment-api', 'gradebook-service', 'analytics-worker', 'content-cms', 'mobile-learning', 'support-bot'],
    integrations: ['Canvas LTI', 'Zoom', 'Turnitin', 'Stripe', 'Google Classroom', 'BigQuery'],
    personas: ['student', 'instructor', 'program manager', 'teaching assistant', 'support advisor'],
    workflows: ['assignment submission', 'grade override', 'course publish', 'attendance sync', 'at-risk learner outreach'],
    qaFocus: ['deadline timezone', 'retake rules', 'screen reader flow', 'LTI launch', 'grade export'],
    incidentThemes: ['assessment submission spike', 'video classroom launch failure', 'gradebook calculation bug', 'content publish rollback'],
  },
  {
    key: 'cybersecurity',
    name: 'Cybersecurity',
    projectName: 'SentinelGrid Security Operations Platform',
    description: 'Build threat detection, case management, asset inventory, response automation, and compliance evidence.',
    summary: 'Cybersecurity backlog covering alert triage, SIEM ingest, response playbooks, vulnerability workflows, and compliance reporting.',
    startOffsetDays: 30,
    durationDays: 120,
    epics: ['Alert triage', 'SIEM ingestion', 'Case management', 'Response automation', 'Asset inventory', 'Vulnerability workflow', 'Threat intel', 'Compliance evidence'],
    components: ['soc-console', 'ingest-api', 'rules-engine', 'case-service', 'automation-runner', 'asset-graph', 'vuln-service', 'evidence-exporter'],
    integrations: ['Splunk', 'CrowdStrike', 'Okta', 'AWS Security Hub', 'Jira', 'ServiceNow'],
    personas: ['SOC analyst', 'incident commander', 'security engineer', 'compliance manager', 'IT asset owner'],
    workflows: ['alert deduplication', 'case escalation', 'playbook approval', 'vulnerability exception', 'evidence collection'],
    qaFocus: ['tenant isolation', 'alert burst handling', 'playbook dry-run', 'RBAC bypass attempts', 'audit evidence immutability'],
    incidentThemes: ['SIEM ingest pressure', 'false positive rule rollout', 'automation token expiry', 'asset sync gap'],
  },
  {
  key: 'travel',
  name: 'Travel',
  projectName: 'TripNexus Travel Booking Platform',
  description: 'Build booking, pricing, itinerary, cancellation, and supplier integration workflows for travel operations.',
  summary: 'Travel backlog covering booking flow, payment capture, dynamic pricing, itinerary changes, supplier sync, and refund operations.',
  startOffsetDays: 320,
  durationDays: 240,
  epics: ['Flight booking', 'Hotel reservation', 'Dynamic pricing', 'Itinerary management', 'Refund workflow', 'Supplier sync', 'Travel insurance', 'Loyalty rewards'],
  components: ['booking-web', 'pricing-service', 'supplier-gateway', 'itinerary-api', 'refund-worker', 'mobile-travel', 'admin-console', 'notification-service'],
  integrations: ['Amadeus', 'Sabre', 'Stripe', 'SendGrid', 'Google Maps', 'Datadog'],
  personas: ['traveler', 'travel agent', 'support specialist', 'supplier manager', 'finance operator'],
  workflows: ['flight search', 'booking confirmation', 'refund request', 'itinerary change', 'supplier reconciliation'],
  qaFocus: ['timezone conversion', 'duplicate booking prevention', 'refund edge cases', 'supplier timeout retry', 'currency conversion'],
  incidentThemes: ['supplier API outage', 'payment capture mismatch', 'booking confirmation delay', 'refund worker backlog'],
},
{
  key: 'real-estate',
  name: 'Real Estate',
  projectName: 'PropVista Property Management Suite',
  description: 'Manage rental listings, tenant applications, lease workflows, maintenance tickets, and owner reporting.',
  summary: 'Real estate backlog covering property listings, tenant screening, lease generation, maintenance operations, and payments.',
  startOffsetDays: 280,
  durationDays: 230,
  epics: ['Listing management', 'Tenant screening', 'Lease workflow', 'Maintenance tickets', 'Rent payments', 'Owner dashboard', 'Document signing', 'Inspection scheduling'],
  components: ['property-web', 'tenant-portal', 'lease-service', 'maintenance-api', 'payment-worker', 'owner-dashboard', 'document-service', 'inspection-mobile'],
  integrations: ['DocuSign', 'Stripe', 'Experian', 'Google Maps', 'Twilio', 'QuickBooks'],
  personas: ['property manager', 'tenant', 'owner', 'maintenance technician', 'leasing agent'],
  workflows: ['tenant application', 'lease renewal', 'maintenance request', 'rent collection', 'property inspection'],
  qaFocus: ['document permission', 'payment retry', 'lease date validation', 'tenant notification', 'inspection offline sync'],
  incidentThemes: ['rent payment duplicate charge', 'lease document generation failure', 'maintenance queue backlog', 'tenant screening timeout'],
},
{
  key: 'food-delivery',
  name: 'Food Delivery',
  projectName: 'DineSwift Delivery Operations Platform',
  description: 'Support restaurant onboarding, order dispatch, driver tracking, payments, and customer support workflows.',
  summary: 'Food delivery backlog covering live order flow, courier dispatch, restaurant menus, payment reconciliation, and support operations.',
  startOffsetDays: 260,
  durationDays: 220,
  epics: ['Restaurant onboarding', 'Menu management', 'Order dispatch', 'Courier tracking', 'Payment reconciliation', 'Promo campaigns', 'Customer support', 'Delivery quality'],
  components: ['consumer-app', 'restaurant-portal', 'dispatch-engine', 'courier-mobile', 'menu-service', 'payment-worker', 'support-console', 'promo-api'],
  integrations: ['Stripe', 'Google Maps', 'Twilio', 'Segment', 'Firebase', 'Snowflake'],
  personas: ['customer', 'restaurant owner', 'courier', 'support agent', 'operations manager'],
  workflows: ['order placement', 'restaurant acceptance', 'courier assignment', 'delivery tracking', 'refund handling'],
  qaFocus: ['order state consistency', 'GPS drift handling', 'payment refund cases', 'menu availability sync', 'courier reassignment'],
  incidentThemes: ['dispatch engine delay', 'restaurant tablet offline', 'payment settlement mismatch', 'courier location lag'],
},
{
  key: 'media-streaming',
  name: 'Media Streaming',
  projectName: 'StreamWave Content Delivery Platform',
  description: 'Build subscription video streaming features for content catalog, playback, recommendations, and billing.',
  summary: 'Media streaming backlog covering playback reliability, catalog ingestion, recommendation quality, subscriptions, and device support.',
  startOffsetDays: 240,
  durationDays: 210,
  epics: ['Video playback', 'Content ingestion', 'Recommendation engine', 'Subscription billing', 'Device activation', 'Parental controls', 'Watch history', 'Live event streaming'],
  components: ['web-player', 'mobile-player', 'catalog-api', 'recommendation-service', 'billing-service', 'encoding-worker', 'device-api', 'analytics-worker'],
  integrations: ['AWS MediaConvert', 'Stripe Billing', 'Firebase', 'BigQuery', 'Akamai CDN', 'Datadog'],
  personas: ['viewer', 'content operator', 'support agent', 'marketing manager', 'platform engineer'],
  workflows: ['video playback', 'content publish', 'subscription renewal', 'device login', 'live event monitoring'],
  qaFocus: ['DRM playback', 'subtitle sync', 'billing retry', 'CDN failover', 'device compatibility'],
  incidentThemes: ['CDN latency spike', 'encoding queue backlog', 'subscription renewal failures', 'live stream buffer rate increase'],
},
{
  key: 'govtech',
  name: 'GovTech',
  projectName: 'CivicLink Public Services Portal',
  description: 'Digitize public service applications, citizen identity verification, case routing, and agency reporting.',
  summary: 'GovTech backlog covering citizen services, document submission, case management, identity checks, notifications, and audit reporting.',
  startOffsetDays: 300,
  durationDays: 250,
  epics: ['Citizen onboarding', 'Identity verification', 'Permit applications', 'Case routing', 'Document upload', 'Agency dashboard', 'Notification workflow', 'Audit reporting'],
  components: ['citizen-portal', 'case-service', 'document-api', 'identity-gateway', 'agency-dashboard', 'notification-worker', 'audit-service', 'admin-console'],
  integrations: ['Okta', 'DocuSign', 'Twilio', 'AWS S3', 'Power BI', 'ServiceNow'],
  personas: ['citizen', 'case officer', 'agency admin', 'compliance auditor', 'support specialist'],
  workflows: ['permit application', 'case review', 'document verification', 'citizen notification', 'appeal submission'],
  qaFocus: ['document access control', 'identity retry behavior', 'case SLA tracking', 'audit immutability', 'notification delivery'],
  incidentThemes: ['document upload failure', 'identity provider timeout', 'case routing misconfiguration', 'notification backlog'],
}
];
